### ISSUE TITLE
Installing Distrobox on Pop OS 22.04 fails at phase 3 cannot create mount target file: /usr/lib64/nvidia/xorg/nvidia_drv.so

### ISSUE THREAD

**Issue by JoelSerranoLozano** [alvr-org/ALVR-Distrobox-Linux-Guide#10]
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/12743050/setup.log)

**Comment by JoelSerranoLozano** [comment]
I am using a laptop which has optimus though

**Comment by kst21** [comment]
Try to change in file setup-process.sh line 53 
from "git clone https://github.com/89luca89/distrobox.git distrobox-git"
to "git clone https://github.com/89luca89/distrobox.git --branch 1.5.0.1 distrobox-git"

**Comment by Meister1593** [comment]
Is this still an issue? Please reopen if latest doesnt work still.
