### ISSUE TITLE
Installation fails at Phase 3 - Distrobox nvidia integration fail

### ISSUE THREAD

**Issue by xylo04** [alvr-org/ALVR-Distrobox-Linux-Guide#13]
Attaching [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13621484/setup.log) as requested. But here's the interesting part:

```
Starting container...                   	 [ OK ]
Installing basic packages...            	 [ OK ]
Setting up devpts mounts...             	 [ OK ]
Setting up read-only mounts...          	 [ OK ]
Setting up read-write mounts...         	 [ OK ]
Setting up host's sockets integration...	 [ OK ]
Setting up host's nvidia integration... 	 Error: An error occurred
 : Couldn't install distrobox container first time at phase 3, please report it as an issue with attached setup.log from the directory.
```

**Comment by Meister1593** [comment]
Hello. Thank you for trying out this.
Can you please try to do the following to diagnose the issue:
1. Uninstall it first using uninstall.sh
2. Open file `setup-phase-1-2.sh`
3. Go to line 134 with `distrobox-enter --name "$container_name" --additional-flags "--env XDG_CURRENT_DESKTOP=X-Generic --env prefix='$prefix' --env container_name='$container_name'" -- ./setup-phase-3.sh` on it
4. Replace with `distrobox-enter --verbose --name "$container_name" --additional-flags "--env XDG_CURRENT_DESKTOP=X-Generic --env prefix='$prefix' --env container_name='$container_name'" -- ./setup-phase-3.sh` (i added --verbose to see what's possibly wrong)
5. Start setup.sh again to re-do setup.
6. Attach setup.log here again

**Comment by xylo04** [comment]
Attached new [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13626423/setup.log). While I don't really know what I'm looking at, this looks interesting:

```
++ dirname /usr/lib64/nvidia/xorg/libglxserver_nvidia.so.545.29.06
+ mkdir -p /usr/lib64/nvidia/xorg
mkdir: cannot create directory ‘/usr/lib64/nvidia/xorg’: Read-only file system
```

**Comment by rateforx** [comment]
I seem to have a similar problem.

> Setting up host's nvidia integration... 	 Error: An error occurred
>  : Couldn't install distrobox container first time at phase 3, please report it as an issue with attached setup.log from the directory.

@Meister1593  I've also followed the steps you provided.
Here's my log file: [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13627858/setup.log)

In my case this line is also present.
> mkdir: cannot create directory ‘/usr/lib64/nvidia/xorg’: Read-only file system

@xylo04 Is your `/usr/lib64` mounted to an external drive by any chance?

**Comment by Meister1593** [comment]
If this is upstream issue, we can report it there, but for now we will check if it has been fixed. From brief issues check i couldn't find if it was fixed or not, so one (or both) if you do this:
1. Uninstall it again
2. Go to setup-phase-1-2.sh 
3. Go to line 59 where `distrobox_commit="1.6.0.1"` is
4. Change to `distrobox_commit="3435f4d27070a99668bfa29a3e508db4ecc09009"` (this is latest commit on distrobox right now, it seems like it is preparing for release)
5. Save, start setup again.
6. Attach log after fail (if it happened)

**Comment by rateforx** [comment]
It failed again, same error. [2-setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13627926/2-setup.log)

**Comment by Meister1593** [comment]
> It failed again, same error. [2-setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13627926/2-setup.log)

you didn't seem to download it from scratch, i see it uses it from `.local/bin`, did you run uninstall?

Any weirdness while removing it with uninstall.sh?...

**Comment by rateforx** [comment]
I did. Everything went smoothly there.

Does it matter if I run the setup and uninstall scripts with sudo?

**Comment by Meister1593** [comment]
Can you post `ls ~/.local/bin` ? seems like there is distrobox and podman from somewhere

You didn't use distrobox and podman before, right?

**Comment by Meister1593** [comment]
> I did. Everything went smoothly there.
> 
> Does it matter if I run the setup and uninstall scripts with sudo?

It does. Don't run it with sudo, ever
it's completely rootless

**Comment by rateforx** [comment]
Right.

```sh
snippy@snippy:~/ALVR-Distrobox-Linux-Guide$ ls ~/.local/bin
distrobox           distrobox-create  distrobox-ephemeral  distrobox-generate-entry  distrobox-init  distrobox-rm    distrobox-upgrade
distrobox-assemble  distrobox-enter   distrobox-export     distrobox-host-exec       distrobox-list  distrobox-stop  podman

```

**Comment by Meister1593** [comment]
Run uninstall without sudo and setup without sudo

**Comment by rateforx** [comment]
```sh
snippy@snippy:~/ALVR-Distrobox-Linux-Guide$ ./uninstall.sh 
 : Using default installation with default name
localuser:snippy being added to access control list
/home/snippy/.local/bin/podman
/home/snippy/.local/bin/distrobox
 : Using system podman and distrobox
 : If you're using sudo, press enter, otherwise please write it as-is now and then press enter to confirm deletion of installation folder with arch-alvr container.
```

I am not sure if I am understanding the instructions here correctly then. What should I input?

**Comment by Meister1593** [comment]
Just press enter, you're using sudo. This is case for more distros that don't utilise sudo at all (and use doas and others)

I will now add gates for root being used on scripts and will make this message appear only if you don't have sudo

**Comment by rateforx** [comment]
I wasn't running setup with sudo before, just to be clear. But I did try to run the uninstall with sudo at one point.

> Run uninstall without sudo and setup without sudo

Done. Same result. [3-setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13628017/3-setup.log)

**Comment by Meister1593** [comment]
Seems like we need to report upstream... I will create issue about this and link here

**Comment by Meister1593** [comment]
Can one of you also try to do such test:

All within one terminal session:
```bash
mkdir test-nvidia
cd test-nvidia
wget -O podman https://github.com/89luca89/podman-launcher/releases/download/v0.0.3/podman-launcher-amd64
chmod +x podman
mkdir -p "$HOME/.local/bin"
mv podman "$HOME/.local/bin"
git clone https://github.com/89luca89/distrobox.git distrobox
cd distrobox
mkdir -p "$HOME/.local/bin"
./install
cd ..
export PATH="$HOME/.local/bin:$PATH"
distrobox-create --verbose --image docker.io/library/archlinux:latest --name test-nvidia --home ~/test-nvidia/test-nvidia --nvidia 2>&1 | tee ~/test-nvidia/distrobox-create.log
distrobox-enter --verbose --name test-nvidia 2>&1 | tee ~/test-nvidia/distrobox-enter.log
```
For cleanup (within same terminal session, exit container with ctrl + d if you stayed in it):
```bash
podman system reset
rm "$HOME/.local/bin/podman"
curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/uninstall | sh
```

does it fail?
Attach `distrobox-create.log`, `distrobox-enter.log` here if it doesn't

Also keep in mind i just made this script on the fly, it might be slightly wrong

**Comment by rateforx** [comment]
It does fail. Same error as before.
[distrobox-create.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13628122/distrobox-create.log)
[distrobox-enter.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13628123/distrobox-enter.log)

**Comment by Meister1593** [comment]
distrobox-create.log is kinda weird though

**Comment by Meister1593** [comment]
I will attach distrobox-enter.log into distrobox issue if that's okay.

**Comment by Meister1593** [comment]
Both logs kinda weird to be honest, there should be way more logging from this

**Comment by rateforx** [comment]
Maybe something wrong with the script? There was way more output in the console.

**Comment by Meister1593** [comment]
Yes it is... i think i forgot to add redirect

**Comment by Meister1593** [comment]
i changed script above now, try again

**Comment by rateforx** [comment]
Complete logs:
[distrobox-create.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13628204/distrobox-create.log)
[distrobox-enter.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13628205/distrobox-enter.log)

**Comment by Meister1593** [comment]
For now, we wait until distrobox dev answers what's wrong there.
Thank you for your help with getting logs and testing!

**Comment by PurabIsMe** [comment]
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/14217627/setup.log)
I got the same problem, any update?

**Comment by Meister1593** [comment]
If anyone got time to check out latest changes, do it, i will close this issue in a few days/week as fixed.

**Comment by xylo04** [comment]
I used `git clean`, `git pull` and `./setup.sh` with similar results. Failed in phase 3.

[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/14552814/setup.log)

```
Starting container...                            [ OK ]
Executing pre-init hooks...                      [ OK ]
Installing basic packages...                     [ OK ]
Setting up devpts mounts...                      [ OK ]
Setting up read-only mounts...                   [ OK ]
Setting up read-write mounts...                  [ OK ]
Setting up host's sockets integration...         [ OK ]
Setting up host's nvidia integration...          Error: An error occurred
 : Couldn't install distrobox container first time at phase 3, please report setup.log to https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/issues.
```

Edit: same result on `nightly` branch.

**Comment by tobico** [comment]
I'm seeing this issue too. Running a fresh install of Pop_OS with Nvidia drivers on my XPS 17 laptop.

[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/14622811/setup.log)

**Comment by Meister1593** [comment]
I updated main branch with fresh distrobox, can some of you try again? i'm not sure whats wrong as before i upgraded past that error which caused nvidia issue, maybe different one this time?
@xylo04 nightly branch doesn't exist anymore, i merged it into main as a toggle

**Comment by xylo04** [comment]
Same result at 18469c01b033f618268f44cf517061e01c08d0e5 ☹️ 

```
Setting up host's nvidia integration...          Error: An error occurred
 : Couldn't install distrobox container first time at phase 3, please report setup.log to https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/issues.
```

[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/14643470/setup.log)

**Comment by TrevorDeyo** [comment]
Starting container...                   	 [ OK ]
Installing basic packages...            	 [ OK ]
Setting up devpts mounts...             	 [ OK ]
Setting up read-only mounts...          	 [ OK ]
Setting up read-write mounts...         	 [ OK ]
Setting up host's sockets integration...	 [ OK ]
Setting up host's nvidia integration... 	 Error: An error occurred
 : Couldn't install distrobox container first time at phase 3, please report setup.log to https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/issues.

[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/15343202/setup.log)

**Comment by Svampebob1** [comment]
Hi,
I'm having the same problem. Any progress here?
