### ISSUE TITLE
Container uses ID mappings but doesn't map UID 0

### ISSUE THREAD

**Issue by kingoftheconnors** [alvr-org/ALVR-Distrobox-Linux-Guide#14]
When trying to install using Distrobox, I get this error during phase 2 (full log copied below):

```
 : Using default installation with default name
pkill: killing pid 3722 failed: Operation not permitted
NAME="SteamOS"
PRETTY_NAME="SteamOS"
VERSION_CODENAME=holo
ID=steamos
ID_LIKE=arch
ANSI_COLOR="1;35"
HOME_URL="https://www.steampowered.com/"
DOCUMENTATION_URL="https://support.steampowered.com/"
SUPPORT_URL="https://support.steampowered.com/"
BUG_REPORT_URL="https://support.steampowered.com/"
LOGO=steamos
VARIANT_ID=steamdeck-rc
BUILD_ID=20230831.1
VERSION_ID=3.4.10
 : Phase 1
/home/deck/.local/bin/podman
/home/deck/.local/bin/distrobox
 : Phase 2
localuser:deck being added to access control list
/home/deck/.local/bin/podman
/home/deck/.local/bin/distrobox
 : Using system podman and distrobox
amd
Trying to pull docker.io/library/archlinux:latest...
Getting image source signatures
Copying blob sha256:3cf0cec5055ad0de6e32a3a567d0d2df42fdf3517493daad0887502a27f516d9
Copying blob sha256:455582f1306491ad2d8a6ac4475020ad953d50f499850ebafb08e0222bbcc914
Copying config sha256:1e73f0f3a7ab45c7f43cd2b53dc7d86376505a8ae116a58b33abac4a257e093d
Writing manifest to image destination
1e73f0f3a7ab45c7f43cd2b53dc7d86376505a8ae116a58b33abac4a257e093d
Creating 'arch-alvr' using image docker.io/library/archlinux:latest      [ OK ]
Distrobox 'arch-alvr' successfully created.
To enter, run:

distrobox enter arch-alvr

Error: 1 error occurred:
        * container uses ID mappings ([]specs.LinuxIDMapping{specs.LinuxIDMapping{ContainerID:0x3e8, HostID:0x0, Size:0x1}}), but doesn't map UID 0
 : Couldn't create distrobox container, please report it to maintainer.
 : GPU: amd; AUDIO SYSTEM: pipewire
```

I've already tried using `./uninstall.sh` and then `./setup.sh`. So the above log is the shorter version, but the error still happens.

If it helps, I get this error when testing pipewire:
```
(125)(deck@steamdeck ALVR-Distrobox-Linux-Guide)$ pipewire
[W][02596.812192] mod.rt       | [     module-rt.c:  297 translate_error()] RTKit error: org.freedesktop.DBus.Error.Failed
[W][02596.812424] mod.rt       | [     module-rt.c:  622 set_nice()] could not set nice-level to -11: Input/output error
[E][02596.813507] mod.protocol-native | [module-protocol-:  728 lock_socket()] server 0x55eb6610d410: unable to lock lockfile '/run/user/1000/pipewire-0.lock': Resource temporarily unavailable (maybe another daemon is running)
[E][02596.813644] pw.conf      | [          conf.c:  594 load_module()] 0x55eb660cc1e0: could not load mandatory module "libpipewire-module-protocol-native": Resource temporarily unavailable
[E][02596.813837] default      | [      pipewire.c:  125 main()] failed to create context: Resource temporarily unavailable
```

**Comment by Meister1593** [comment]
Try doing `./uninstall.sh` and using https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/tree/lilipod branch instead

It's experimental branch without podman (uses lilipod instead), which sometimes causes problems, and lilipod is very lightweight/simple

**Comment by kingoftheconnors** [comment]
Thanks for the response! I gave it a shot, and it got all the way to Phase 3 (which is further than before!). Then it hit a different-looking error

```
Creating 'arch-alvr' using image registry.fedoraproject.org/fedora-toolbox:38   proc_utils.go:194 [error] exit status 1
2023/12/22 16:01:26 exit status 1
 [ ERR ]
proc_utils.go:194 [error] exit status 1
2023/12/22 16:01:26 exit status 1
 : Couldn't install distrobox container first time at phase 3, please report it as an issue with attached setup.log from the directory.
```

Setup.log:
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13756717/setup.log)

**Comment by Meister1593** [comment]
Hm, i think steam deck doesn't have `getsubids` command (judging by this https://github.com/89luca89/lilipod/blob/main/pkg/procutils/proc_utils.go#L192C34-L192C43 being a problem point) and as such, can't use lilipod... that's not good
Can you check if you can use it? (without anything, just plain `getsubids`)

**Comment by kingoftheconnors** [comment]
It seems to work fine

```
(1)(deck@steamdeck ~)$ getsubids
Usage: getsubids [-g] user
    list subuid ranges for user
    pass -g to list subgid ranges
```

**Comment by Meister1593** [comment]
Try doing `getsubids $(whoami)`, what's the output?

**Comment by kingoftheconnors** [comment]
aha

```
(130)(deck@steamdeck ~)$ getsubids $(whoami)
Error fetching ranges
```

**Comment by Meister1593** [comment]
what is the output of `whoami` and `pacman -Q shadow` ?

**Comment by kingoftheconnors** [comment]
```
(deck@steamdeck ~)$ whoami
deck
(deck@steamdeck ~)$ pacman -Q shadow
shadow 4.11.1-1

(1)(deck@steamdeck ~)$ getsubids -g deck
Error fetching ranges
(1)(deck@steamdeck ~)$ getsubids deck
Error fetching ranges
```

**Comment by Meister1593** [comment]
I can't seem to install 4.11.1-1 package on Arch, seems like it's corrupted?...

4.11.1-2 works fine

I feel like it should be reported to steam/steamos support

**Comment by kingoftheconnors** [comment]
What's it take to install 4.11.1-2?

**Comment by Meister1593** [comment]
Unlocking steamos read-only partition and trying to update shadow package specifically

**Comment by kingoftheconnors** [comment]
Turns out, the package HAS been updated on SteamOS on an update that I hadn't downloaded yet!

Here's what I'm getting now:

```
/usr/bin/distrobox
 : Phase 2
localuser:deck being added to access control list
which: no lilipod in (/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
amd
Invalid input lilipod.
The available choices are: 'autodetect', 'podman', 'docker'
pulling image manifest: index.docker.io/library/archlinux:latest
pulling layer 455582f1306491ad2d8a6ac4475020ad953d50f499850ebafb08e0222bbcc914.tar.gz
Copying blob sha256:455582f1306491ad2d8a6ac4475020ad953d50f499850ebafb08e0222bbcc914   1% |                                                                                                                   
Copying blob sha256:3cf0cec5055ad0de6e32a3a567d0d2df42fdf3517493daad0887502a27f516d9 100% |██████████████████████████████| (47 MB/s)
saving layer sha256:3cf0cec5055ad0de6e32a3a567d0d2df42fdf3517493daad0887502a27f516d9 done
saving manifest for index.docker.io/library/archlinux:latest
saving config for index.docker.io/library/archlinux:latest
saving metadata for index.docker.io/library/archlinux:latest
done
bff6ec3f9f1dfc505287643d8c56a967
Creating 'arch-alvr' using image docker.io/library/archlinux:latest      [ OK ]
Distrobox 'arch-alvr' successfully created.
To enter, run:

distrobox enter arch-alvr

Invalid input lilipod.
The available choices are: 'autodetect', 'podman', 'docker'
/usr/bin/distrobox-generate-entry: line 248: container_manager_cp_command: unbound variable
 : Couldn't create distrobox container, please report it to maintainer.
 : GPU: amd; AUDIO SYSTEM: pipewire
```

**Comment by Meister1593** [comment]
Full log? I think you started to use other distrobox (steamos might include it now)

**Comment by kingoftheconnors** [comment]
Here: 
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13757507/setup.log)

**Comment by kingoftheconnors** [comment]
When I uninstall and redo setup, I get a slightly different result: 
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13757515/setup.log)

**Comment by Meister1593** [comment]
yes... they started shipping distrobox with themselves
I guess i need to adjust script to completely get rid off system-wide installed tools (distrobox was last one to be honest)

I will check what i can do tomorrow or later, wait for now

**Comment by kingoftheconnors** [comment]
Understood! Thank you so much.

**Comment by kingoftheconnors** [comment]
@Meister1593 Any luck on this?

**Comment by Meister1593** [comment]
Sorry, haven't had a time yet for this, will write off whenever i finish with script and it would need more testing

**Comment by kingoftheconnors** [comment]
@Meister1593 Understood. Do you think it will be possible for it to be ready before the 6th? I will be going out of town, so I won't be able to test the script for a couple weeks after that.

**Comment by Meister1593** [comment]
I might be able to put out refreshed script in matter of hours

**Comment by Meister1593** [comment]
I updated main branch, you can check it out if you want
Unfortunately i discovered that issue with vrwebhelper (and thus, half of steamvr interface) not running is... somewhat mystery to me, i did manage to make it work by preloading libs manually  in vrwebhelper.sh but it was really hacky and i'm not sure why it doesn't work. 
Possibly related to locales, but i did set them up properly and it worked before...

**Comment by kingoftheconnors** [comment]
I gave it a pull and it got to phase 3! It asked me to log in to steam and install steamVR, so I'll install it and test it out for real tomorrow!

**Comment by kingoftheconnors** [comment]
It installed successfully! Thank you!
