### ISSUE TITLE
Installation freeze on phase 2

### ISSUE THREAD

**Issue by swaiku** [alvr-org/ALVR-Distrobox-Linux-Guide#15]
When the script start steamVR to generate startup files. it freezes to this step even if the launch is finished. I have waited about 10 minutes without any success.

Here is the [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13762142/setup.log)

**Comment by Meister1593** [comment]
did you try to open steamvr manually after that? does steam show steamvr is running?

**Comment by swaiku** [comment]
The script start automatically steamvr and steamvr is running, but the script don't go to the next step. I tried to start manually. it start but it don't change anything for the script.

**Comment by Meister1593** [comment]
Ah i understand now...
Seems like it couldn't find startup steamvr process and kept waiting, possibly something to do with how script waits with `until`

Can you change `helper-functions.sh` and replace 2 functions with those contents bellow?
```bash
function wait_for_initial_steamvr() {
   for steamvr_process in vrmonitor vrwebhelper vrserver; do
      while ! pgrep "$steamvr_process" > /dev/null; do
         echo "waiting for initial steamvr"
         sleep 1
      done
   done
}

function wait_for_full_steamvr() {
   for steamvr_process in "${STEAMVR_PROCESSES[@]}"; do
      while ! pgrep "$steamvr_process" > /dev/null; do
         echo "waiting for steamvr"
         sleep 1
      done
   done
}
```
And try again installing it, report with logs that it produced.

**Comment by swaiku** [comment]
So i tried, and it keep writing the first one. Here the [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13766690/setup.log)

I tried with the automatic start and manually

**Comment by Meister1593** [comment]
While this is happening, can you do in separate terminal `source setup-env.sh && distrobox-enter arch-alvr` and check for processes with `ps aux | grep -i vr` from inside container that way, what will it show?
Also do it from outside with same command
Share outputs

**Comment by swaiku** [comment]
Here outputs :

outside the container : [output_from_outside_container.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13766788/output_from_outside_container.log)
inside the container : [output_ps.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13766789/output_ps.log)

**Comment by Meister1593** [comment]
Seems like vrwebhelper isn't running... hmm, something is wrong
Does steam work fine by itself? Like, shop and everything works fine?

**Comment by swaiku** [comment]
Steam works perfectly.
Interesting thing to note it's not possible to access to the settings of steamvr when it launched. Maybe linked with the new update ?

**Comment by Meister1593** [comment]
> Steam works perfectly. Interesting thing to note it's not possible to access to the settings of steamvr when it launched. Maybe linked with the new update ?

No, i'm on new update and interface works
The fact that vrwebhelper doesn't work is what makes steamvr settings inaccessible...
Can you check if there was recent coredump in `coredumpctl` from vrwebhelper? and check it with `coredumpctl dump pid` (where pid is short number from coredumpctl)

**Comment by swaiku** [comment]
So i have test again. I had no match with coredumpctl. I have tried to put steamvr to beta and now vrwebhelper works but the script is still blocked. Here the coredumctl now : 

`
Mon 2023-12-25 18:26:14 CET 142659 1000 1000 SIGSEGV present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             4.6M
Mon 2023-12-25 18:26:15 CET 142781 1000 1000 SIGSEGV present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             4.4M
Mon 2023-12-25 18:26:16 CET 142873 1000 1000 SIGSEGV present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             4.4M
Mon 2023-12-25 18:26:40 CET 142631 1000 1000 SIGTRAP present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             7.2M
Mon 2023-12-25 18:37:14 CET 160220 1000 1000 SIGSEGV present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             4.6M
Mon 2023-12-25 18:37:15 CET 160347 1000 1000 SIGSEGV present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             4.4M
Mon 2023-12-25 18:37:15 CET 160468 1000 1000 SIGSEGV present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             4.4M
Mon 2023-12-25 18:38:01 CET 160182 1000 1000 SIGTRAP present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             7.2M
Mon 2023-12-25 18:38:20 CET 161261 1000 1000 SIGSEGV present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             4.5M
Mon 2023-12-25 18:38:21 CET 161389 1000 1000 SIGSEGV present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             4.4M
Mon 2023-12-25 18:38:22 CET 161497 1000 1000 SIGSEGV present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             4.4M
Mon 2023-12-25 18:38:27 CET 161218 1000 1000 SIGTRAP present  /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper                             5.9M
`

And if i take the last one :


[swaiku@arch-alvr ALVR-Distrobox-Linux-Guide]$ coredumpctl dump 161218
           PID: 161218 (vrwebhelper)
           UID: 1000 (swaiku)
           GID: 1000 (swaiku)
        Signal: 5 (TRAP)
     Timestamp: Mon 2023-12-25 18:38:27 CET (3min 40s ago)
  Command Line: ./vrwebhelper
    Executable: /home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/297cf59825564ae9885f1a95a8e17952d7f6b7a839ecfd36d6dac6c2c16b01a8
          Unit: user@1000.service
         Slice: user-1000.slice
     Owner UID: 1000 (swaiku)
       Boot ID: efc9bd513a65453b845bdd1fe50023a5
    Machine ID: 1f597281e934412fa55bb8cddeb75998
      Hostname: arch-alvr.swa-wst-01
       Storage: /var/lib/systemd/coredump/core.vrwebhelper.1000.efc9bd513a65453b845bdd1fe50023a5.161218.1703525907000000.zst (present)
  Size on Disk: 5.9M
       Message: Process 161218 (vrwebhelper) of user 1000 dumped core.
                
                Stack trace of thread 161218:
                #0  0x00007f86b84bd50b n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x5cbd50b)
                #1  0x00007f86b93bbcce n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x6bbbcce)
                #2  0x00007f86b93bbcfe n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x6bbbcfe)
                #3  0x00007f86b93bbbc6 n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x6bbbbc6)
                #4  0x00007f86b6bc27a7 n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x43c27a7)
                #5  0x00007f86b6bc2691 n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x43c2691)
                #6  0x00007f86b6a6884b n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x426884b)
                #7  0x00007f86b6af879e n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x42f879e)
                #8  0x00007f86b6af8697 n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x42f8697)
                #9  0x00007f86b6ad2795 n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x42d2795)
                #10 0x0000562add1ed323 n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper + 0x66323)
                #11 0x0000562add1d8df0 n/a (/home/swaiku/Apps/ALVR-Distrobox-Linux-Guide/installation/arch-alvr/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/vrwebhelper + 0x51df0)
                #12 0x00007f86b2245cd0 n/a (/run/host/usr/lib/libc.so.6 + 0x27cd0)
                ELF object binary architecture: AMD x86-64

**Comment by Meister1593** [comment]
Okay i'm not sure what to do there other than skip steamvr settings entirely for now so, in `helper-functions.sh` again remove all mentions of `vrwebhelper`, if this doesn't work, check for other processes with `ps aux | grep process` (most likely you would also need to remove `vrdashboard` or `vrstartup`, but do check without `vrwebhelper` first)

**Comment by swaiku** [comment]
I have tried to change the script like this to be more verbose : 

```bash
function wait_for_initial_steamvr() {
   for steamvr_process in vrmonitor vrserver; do
   while ! pgrep "$steamvr_process" > /dev/null; do
        echo "waiting for initial steamvr : $steamvr_process"
       sleep 1
      done
   done
}

function wait_for_full_steamvr() {
   for steamvr_process in "${STEAMVR_PROCESSES[@]}"; do
      while ! pgrep "$steamvr_process" > /dev/null; do
         echo "waiting for steamvr $steamvr_process"
         sleep 1
      done
   done
}
```
There is no success with this. It looks like even the vrserver don't want to start. Here the [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13779435/setup.log)


I have try to remove the `vrserver` too but it doesn't change anything really.

**Comment by Meister1593** [comment]
I updated repository with new version, vrwebhelper (and half of steamvr ui) seems to not work properly under container so i mentioned it in new version, you can use wlxoverlay for now.
Open new issue if you still have them
