### ISSUE TITLE
"Couldn't install distrobox container first time at phase 3" 

### ISSUE THREAD

**Issue by Egless3** [alvr-org/ALVR-Distrobox-Linux-Guide#17]
Linux Mint 21.2 x86_64 (KDE Plasma 5.24.7)

[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13807110/setup.log)

**Comment by Meister1593** [comment]
Please install latest version from this repository and try again, there were a lot of changes and it might work now (or say why it didn't work)
Open new issue if still doesn't work
