### ISSUE TITLE
Couldn't install distrobox container first time at phase 4

### ISSUE THREAD

**Issue by natstott** [alvr-org/ALVR-Distrobox-Linux-Guide#18]
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13811231/setup.log)

Also, a comment that scripts failed a few times at "Running steam once to generate startup files.", after it had reinstalled Steam each time, eventually I realised that I had to quit the instance of Steam that had autolaunched and relaunch Steam.

**Comment by Meister1593** [comment]
Please download latest version from this repo and try again, there were a lot of changes and it might work now (or say why it didn't work)

**Comment by Meister1593** [comment]
Open new issue if you still can't get it to work
