### ISSUE TITLE
Latest Release - cannot create directory ‘/home/nat/ALVR/installation-lilipod/bin’: File exists

### ISSUE THREAD

**Issue by natstott** [alvr-org/ALVR-Distrobox-Linux-Guide#21]
Following update...

Lilipod is downloaded, but can't  create /bin folder to move it to. Lilipod download creates a bash script called "bin" in the target folder.

I put a break in the script and manually created the bin folder (with "bin" script moved to it), then the distrobox install failed.

[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13817104/setup.log)

**Comment by Meister1593** [comment]
Hello
I pushed update to main, can you try again?

**Comment by natstott** [comment]
Thanks.

OK now it creates the bin and share folders in installation-lilipod but still stops at "failed to install lilipod properly" test
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13817396/setup.log)

**Comment by Meister1593** [comment]
What are contents of `installation-lilipod/bin` folder ?

**Comment by natstott** [comment]
-rwxr-xr-x 1 nat nat    2155 Jan  3 09:23 distrobox
-rwxr-xr-x 1 nat nat   12137 Jan  3 09:23 distrobox-assemble
-rwxr-xr-x 1 nat nat   32877 Jan  3 09:23 distrobox-create
-rwxr-xr-x 1 nat nat   19002 Jan  3 09:23 distrobox-enter
-rwxr-xr-x 1 nat nat    5913 Jan  3 09:23 distrobox-ephemeral
-rwxr-xr-x 1 nat nat   15897 Jan  3 09:23 distrobox-export
-rwxr-xr-x 1 nat nat   11749 Jan  3 09:23 distrobox-generate-entry
-rwxr-xr-x 1 nat nat    6035 Jan  3 09:23 distrobox-host-exec
-rwxr-xr-x 1 nat nat   64912 Jan  3 09:23 distrobox-init
-rwxr-xr-x 1 nat nat    7857 Jan  3 09:23 distrobox-list
-rwxr-xr-x 1 nat nat   11787 Jan  3 09:23 distrobox-rm
-rwxr-xr-x 1 nat nat    8478 Jan  3 09:23 distrobox-stop
-rwxr-xr-x 1 nat nat    7522 Jan  3 09:23 distrobox-upgrade
-rwxrwxr-x 1 nat nat     278 Jan  3 09:23 getsubids
-rwxrwxr-x 1 nat nat 9629696 Sep  7 09:52 lilipod

**Comment by Meister1593** [comment]
Can you try replacing 44 line in setup-phase-1-2.sh
```bash
   # Sanity checks
```
with
```bash
   # Sanity checks
   echog "$(which lilipod)"
   exit 1
```
and rerun setup again
to check what exactly it uses for lilipod in this case

**Comment by natstott** [comment]
: /home/nat/ALVR/ALVR-Distrobox-Linux-Guide/installation-lilipod/bin//lilipod

double slash?

**Comment by Meister1593** [comment]
Yup, seems like it
I pushed fix, try again

**Comment by natstott** [comment]
ok, its passed that check, will let it finish installing.

Thanks for your help.

**Comment by natstott** [comment]
Well, thanks, install finished.

I am however attempting to run it on a Pico 4. The dashboard log reports:

10:50:23.096853302 [WARN] Found incompatible client! Upgrade or downgrade
Expected protocol ID 7466344377858005457, Found 1686174404061257063

This was the ALVR version from sidequest. Any suggestions? I am happy to investigate myself if not.

**Comment by Meister1593** [comment]
Distrobox script downloaded version from nightly into installation-lilipod directory, you should probably use it

Sidequest version might be older than this

When new release comes out, i will switch nightly to release (this is temporary decision to allow for many things to go better than they are on release now)

**Comment by natstott** [comment]
Thanks for your help, install completes smoothly now.
