### ISSUE TITLE
Install errors at phase 2

### ISSUE THREAD

**Issue by tommipontinen76** [alvr-org/ALVR-Distrobox-Linux-Guide#22]
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/13932423/setup.log)

**Comment by Meister1593** [comment]
Hi. Can you try latest script again? 
Uninstall using older `uninstall.sh` and install using newer `setup.sh`.
Older setup might have used podman instead of lilipod and thus why it failed.
