### ISSUE TITLE
Permission denied while trying to connect to the Docker daemon socket

### ISSUE THREAD

**Issue by ToRRent1812** [alvr-org/ALVR-Distrobox-Linux-Guide#23]
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/14202116/setup.log)

**Comment by Meister1593** [comment]
for some reason it tried to use docker instead of lilipod... really weird considering it's already told to use only lilipod

**Comment by ToRRent1812** [comment]
I will disable docker since I don't use it tbh. Maybe something will change.

**Comment by Meister1593** [comment]
I've noticed that script actually didn't use lilipod and instead relied on autodetection, so that's why it used docker first and lilipod last.
Latest version should handle that properly (i needed to export variable to propagate it into distrobox)
