### ISSUE TITLE
Failed installation at Phase 2 - Missing dependenciy newuidmap

### ISSUE THREAD

**Issue by KevSaund** [alvr-org/ALVR-Distrobox-Linux-Guide#33]
Not sure what's happening, here's my [setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/14615341/setup.log)

Any help appreciated.

**Comment by Devallex** [comment]
I'm running Zorin OS, which is based off of Ubuntu. In case anyone has this issue in the future, I fixed this by running `sudo apt install uidmap` in terminal and then typing in my password

Hope this helps someone
