### ISSUE TITLE
Container Setup Complete!  : Phase 3 sudo: effective uid is not 0,

### ISSUE THREAD

**Issue by clemens98** [alvr-org/ALVR-Distrobox-Linux-Guide#36]
Container Setup Complete!
 : Phase 3
sudo: effective uid is not 0, is /usr/sbin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
2024/03/17 09:07:24 exit status 1
 : Couldn't install distrobox container first time at phase 3, please report setup.log to https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/issues.

cant find the issue. no relevant disk is set to nosuid and sudo works fine everywhere else

**Comment by Meister1593** [comment]
hi
are you using external disk (where you install guide) by any chance?

**Comment by clemens98** [comment]
Did at first then switched to main drive no difference

**Comment by Meister1593** [comment]
can you post your `/etc/fstab`? maybe theres something that triggers container mounting...

**Comment by clemens98** [comment]
So container mounting isn't intentional?
Will post the fstab wen I am home in like 8-10hours

**Comment by Meister1593** [comment]
distrobox bind mounts some folders like /etc/hosts, /etc/localtime i think and home folder, i assume something gone wrong in that phase of mounting

**Comment by Meister1593** [comment]
Also put full setup.log later as well, it might contain more useful info

**Comment by clemens98** [comment]
`# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>

#Entry for /dev/nvme0n1p3 :
UUID=e2e0dc14-257b-40a7-8f7a-8ee3774f8524	/	ext4	errors=remount-ro	0	1

/dev/zram0 none swap defaults,pri=100 0 0
#Entry for /dev/nvme0n1p2 :
#UUID=324053CB40539507	/mnt/324053CB40539507	ntfs3	defaults,permission,auto,x-gvfs-show	0	0
#/swapfile	none	swap	sw	0	0
#/swapfile tmpfs /mnt/ramdisk tmpfs   auto rw,user,exec,nodiratime,size=10G  0 0
#WARNING DONT ACTIVATE DRIVE BELOW FOR NOW DUBLICATE ON 4TB drive
UUID=75907c2d-98b4-4caa-a899-0b0345444cd0 /mnt/steam btrfs rw,user,exec,auto,x-gvfs-show 0 0

#/dev/disk/by-uuid/fc082807-f9c3-436b-a7de-7d6374d267b5 /mnt/fc082807-f9c3-436b-a7de-7d6374d267b5 auto nosuid,nodev,nofail,x-gvfs-show 0 0

#RAMDISK
#tmpfs /mnt/ramdisk tmpfs   auto rw,user,exec,nodiratime,size=10G  0 0

#windows 2tb wd drive
/dev/disk/by-partuuid/30774966-bf24-4ac2-aff6-aed74bc92a41 /mnt/windowsHDD2TB lowntfs-3g uid=1000,gid=1000,rw,exec,auto,umask=000 0 0

#1tb ssd

#6tb wd drive
#/dev/disk/by-uuid/e6e46341-afaf-4237-bfc7-d3d818520e31 /mnt/e6e46341-afaf-4237-bfc7-d3d818520e31 auto nosuid,nodev,nofail,x-gvfs-show 0 0
#/dev/disk/by-uuid/e6e46341-afaf-4237-bfc7-d3d818520e31 /mnt/steam_6tbHDD btrfs rw,user,exec,auto,umask=000,x-gvfs-show 0 0

/dev/disk/by-uuid/e6e46341-afaf-4237-bfc7-d3d818520e31 /mnt/steam_6tbHDD btrfs rw,user,exec,auto,x-gvfs-show 0 0
/dev/disk/by-uuid/21047e75-5235-4187-964c-b1e24b093d39 /mnt/6tb-black-recovery auto rw,user,exec,auto,x-gvfs-show 0 0
LABEL=BARACUDA-2.5TB-steam /mnt/BARACUDA-2.5TB-steam auto rw,user,exec,auto,x-gvfs-show 0 0
/dev/disk/by-uuid/4ECC7455CC743973 /mnt/minivolume2tbwddisk auto nosuid,nodev,nofail,x-gvfs-show 0 0
UUID=234D-0318  /boot/efi       vfat    defaults      0       1

/dev/disk/by-uuid/20ad921c-e38a-4881-a761-b96270e81c26 /mnt/bara-recovery auto rw,user,exec,auto,x-gvfs-show 0 0
/dev/disk/by-uuid/dc97cea7-1de2-4984-bef2-e3b1d6ff2c48 /mnt/wSSD1TB auto rw,user,exec,auto,x-gvfs-show 0 0`
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/14639548/setup.log)

**Comment by Meister1593** [comment]
i'm not sure but seems like it's something to do overall with older mint and it not working with containers nicely? i can't tell what exactly is wrong, but i found this
https://superuser.com/questions/1697878/can-t-use-sudo-after-umount-all

**Comment by clemens98** [comment]
tried it besides a few target busy errors during unmount nothing

**Comment by clemens98** [comment]
xhost
access control enabled, only authorized clients can connect
SI:localuser:clemens

is this normal?

**Comment by Meister1593** [comment]
i doubt it's related to main issue, maybe only indirectly

i'm at lost atm with this issue
