### ISSUE TITLE
audio-setup.sh helper does not work if userid != 1000 and will pipe headset mic to headset output instead of expected setup

### ISSUE THREAD

**Issue by kekkels** [alvr-org/ALVR-Distrobox-Linux-Guide#37]
## Description

replace "/run/user/1000" with "$XDG_RUNTIME_DIR"  if user!= 1000 script will not destroy the outputs properly since it won't be able to log them in the dir causing sources and sinks to pile up

the audio-setup.sh helper for pipewire in the setup wizard currently pipes the headset mic back to the audio instead of the expected output sink the routing looks like so:
![bad_configuration](https://github.com/alvr-org/ALVR/assets/155139521/7d3d5adf-55a9-41c1-9909-30eb55eeffe1)
swapping the setup_mic and setup_audio functions orders fixes and results in the routing below: 
![good_configuration](https://github.com/alvr-org/ALVR/assets/155139521/d80ad032-3e64-4cfd-befc-4ea8de952270)

Patch of Both:
```
--- audio-setup.sh	2024-04-22 00:46:05.801436363 -0400
+++ audio-setup-fixed.sh	2024-04-22 01:33:53.171231330 -0400
@@ -41,9 +41,9 @@
   if [[ $USE_HEADSET_MIC == 1 ]]; then
     echo "Creating microphone sink & source and linking alvr playback to it"
     # This sink is required so that it persistently auto-connects to alvr playback later
-    pactl load-module module-null-sink sink_name=ALVR-MIC-Sink media.class=Audio/Sink | tee -a /run/user/1000/alvr-audio
+    pactl load-module module-null-sink sink_name=ALVR-MIC-Sink media.class=Audio/Sink | tee -a "$XDG_RUNTIME_DIR"/alvr-audio
     # This source is required so that any app can use it as microphone
-    pactl load-module module-null-sink sink_name=ALVR-MIC-Source media.class=Audio/Source/Virtual | tee -a /run/user/1000/alvr-audio
+    pactl load-module module-null-sink sink_name=ALVR-MIC-Source media.class=Audio/Source/Virtual | tee -a "$XDG_RUNTIME_DIR"/alvr-audio
     # We link them together
     pw-link ALVR-MIC-Sink:monitor_FL ALVR-MIC-Source:input_FL
     pw-link ALVR-MIC-Sink:monitor_FR ALVR-MIC-Source:input_FR
@@ -57,14 +57,14 @@
   echo "Unloading audio, microphone sink & source"
   while read -r line; do
     pactl unload-module "$line"
-  done <"/run/user/1000/alvr-audio"
-  >/run/user/1000/alvr-audio
+  done <""$XDG_RUNTIME_DIR"/alvr-audio"
+  >"$XDG_RUNTIME_DIR"/alvr-audio
 }
 
 function setup_audio() {
   if [[ $USE_HEADSET_AUDIO == 1 ]]; then
     echo "Setting up audio"
-    pactl load-module module-null-sink sink_name=ALVR-AUDIO-Sink media.class=Audio/Sink | tee -a /run/user/1000/alvr-audio
+    pactl load-module module-null-sink sink_name=ALVR-AUDIO-Sink media.class=Audio/Sink | tee -a "$XDG_RUNTIME_DIR"/alvr-audio
     pactl set-default-sink ALVR-AUDIO-Sink
     pactl move-source-output "$(get_playback_source_output_id alsa_capture.vrserver)" "$(get_sink_id_by_name ALVR-AUDIO-Sink)"
   fi
@@ -73,8 +73,8 @@
 case $ACTION in
 connect)
   unload_modules
-  setup_audio
   setup_mic
+  setup_audio
   ;;
 disconnect)
   unload_modules
```
[audio-setup.txt](https://github.com/alvr-org/ALVR/files/15058104/audio-setup.txt)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:7800X3D

**GPU**:3080Ti

**GPU Driver Version**:550.76-1

**Audio**: pipewire

### Installation
**ALVR Version**: 20.7.1

**ALVR Settings File**:https://pastebin.com/rxWHtCmp

**SteamVR Version**:2.4.4

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Arch Linux

**Comment by Meister1593** [comment]
file is here https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/blob/main/audio-setup.sh
