### ISSUE TITLE
Couldn't install distrobox container first time at phase 4

### ISSUE THREAD

**Issue by doombadroid** [alvr-org/ALVR-Distrobox-Linux-Guide#39]
[setup.log](https://github.com/user-attachments/files/15860091/setup.log)

No idea what went wrong here. The log doesn't seem to point to anything just exit 1 and no further elaboration 

POP_OS 2.04 with an Nvidia RTX 4090 Driver ver 550

**Comment by raum-dellamorte** [comment]
[setup.log](https://gist.github.com/raum-dellamorte/8bfb72516ede6ce630e00d8f10f5f952)

Same. I assume you also were trying to use nightly?

`env.sh -> IS_NIGHTLY=1`

Looking into where it died, the wget for the ALVR-nightly Appimage failed.
```
$> wget --show-progress 'https://github.com/alvr-org/ALVR-nightly/releases/latest/download/ALVR-x86_64.AppImage' 
--2024-07-04 12:31:21--  https://github.com/alvr-org/ALVR-nightly/releases/latest/download/ALVR-x86_64.AppImage
Resolving github.com (github.com)... 140.82.116.4
Connecting to github.com (github.com)|140.82.116.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/alvr-org/ALVR-nightly/releases/download/v21.0.0-dev01+nightly.2024.07.03/ALVR-x86_64.AppImage [following]
--2024-07-04 12:31:22--  https://github.com/alvr-org/ALVR-nightly/releases/download/v21.0.0-dev01+nightly.2024.07.03/ALVR-x86_64.AppImage
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2024-07-04 12:31:22 ERROR 404: Not Found.
```

And so we go deeper and learn that ALVR-nightly is no longer maintaining an Appimage!

So ALVR-Distrobox-Linux-Guide needs to be updated to use the [tarball](https://github.com/alvr-org/ALVR-nightly/releases/latest/download/alvr_streamer_linux.tar.gz) in the case of IS_NIGHTLY=1, it seems.

**Comment by Meister1593** [comment]
To be completely honest, distrobox installation method could soon be deprecated/archived in favor of better explanation of how to do it on alvr side (already partially done, hybrid GPU just needs better explanation) + alvr flatpak getting nvidia support as well, which should work everywhere, also launcher is getting close to release

**Comment by doombadroid** [comment]
> To be completely honest, distrobox installation method could soon be deprecated/archived in favor of better explanation of how to do it on alvr side (already partially done, hybrid GPU just needs better explanation) + alvr flatpak getting nvidia support as well, which should work everywhere, also launcher is getting close to release

Rough ETA on Nvidia flatpak support? Because that would solve pretty much all of my issues
