### ISSUE TITLE
Installation not working, OCI runtime error

### ISSUE THREAD

**Issue by Nebulon-BFrigateFTW** [alvr-org/ALVR-Distrobox-Linux-Guide#7]
Getting `Error: OCI runtime error: unable to start container "e87056250d793a9361dfbc092ee848a9d0e19ef37ba2b604877fc91fa7107f5a": crun: sethostname: Invalid argument` both when running setup and trying to start afterwards.
[setup.log](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/files/11857894/setup.log)

**Comment by Meister1593** [comment]
hello, what is your distribution?

**Comment by Meister1593** [comment]
Many things have changed, i would try fresh installation again. If it doesn't work still, please open new issue.
