### ISSUE TITLE
Steam displays a missing internet connection error on Distrobox

### ISSUE THREAD

**Issue by unclamped** [alvr-org/ALVR-Distrobox-Linux-Guide#8]
![image](https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/assets/104658278/746a2160-1f0b-45a9-8028-c3d77992b6e5)
Fedora 38, I can ping google.com and steampowered.com from a shell in Distrobox, but Steam fails for some reason

**Comment by unclamped** [comment]
Seems like running the command `sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf` makes Steam boot up just fine :thinking:

**Comment by Meister1593** [comment]
i have no idea what's wrong there to be honest, im on silverblue 38 myself

**Comment by Meister1593** [comment]
This looks like a problem with either distrobox itself, or something else... I will close it as i don't know what to do with it atm.
